$(function(){
	$('.btn_rsrv').click(function(){
		$('.cancel_view').hide();
		$('.box_customer').show();
	});
	$('.btn_cancel').click(function(){
		$('.box_customer').hide();
		$('.cancel_view').show();
	});
});